const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=Number(process.env.PORT||3000),KEY=process.env.TIKTOK_CLIENT_KEY||'',SECRET=process.env.TIKTOK_CLIENT_SECRET||'',REDIRECT=process.env.TIKTOK_REDIRECT_URI||`http://localhost:${PORT}/auth/tiktok/callback`,VOICE_PROVIDER=process.env.VOICE_PROVIDER||'',VOICE_CONFIGURED=!!(VOICE_PROVIDER&&process.env.VOICE_API_KEY&&process.env.VOICE_ID),OPENAI_KEY=process.env.OPENAI_API_KEY||'',OPENAI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna',AI_CONFIGURED=!!OPENAI_KEY;const sessions=new Map(),states=new Map(),aiSessions=new Map();
const send=(r,s,t,b)=>{r.writeHead(s,{'Content-Type':t});r.end(b)},json=(r,s,b)=>send(r,s,'application/json',JSON.stringify(b));function sid(r){const m=(r.headers.cookie||'').match(/(?:^|; )sid=([^;]+)/);return m&&m[1]}function aisid(r,res){const m=(r.headers.cookie||'').match(/(?:^|; )ai_sid=([^;]+)/);if(m)return m[1];const id=crypto.randomBytes(24).toString('hex');res.setHeader('Set-Cookie',`ai_sid=${id}; HttpOnly; SameSite=Lax; Secure; Path=/; Max-Age=86400`);return id}
async function askAI(history,language){const name={ur:'Urdu',pa:'Punjabi',en:'Pakistani English'}[language]||'Urdu';const instructions=`You are SARA, a warm Pakistani female AI virtual host. You are an AI and must never claim to be human. Speak naturally in ${name}; understand Roman Urdu, Urdu script, Punjabi and Pakistani English. Keep public livestream replies short, friendly and spontaneous, usually 1-3 sentences. If asked whether you are real, clearly say you are an AI virtual host. Never pressure viewers to send gifts or spend money. Never invent real-time TikTok viewer, gift or battle data.`;const rr=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:OPENAI_MODEL,instructions,input:history,max_output_tokens:180})});const d=await rr.json();if(!rr.ok)throw Error(d.error?.message||'OpenAI request failed');return String(d.output_text||'').trim()}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);
if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'sara-ai-tiktok-live',tiktokOAuthConfigured:!!(KEY&&SECRET),aiConfigured:AI_CONFIGURED,aiModel:AI_CONFIGURED?OPENAI_MODEL:null,voiceConfigured:VOICE_CONFIGURED,voiceProvider:VOICE_PROVIDER||null});
if(u.pathname==='/api/me')return json(res,200,{authenticated:!!(sid(req)&&sessions.has(sid(req)))});
if(u.pathname==='/auth/tiktok'){if(!KEY||!SECRET)return send(res,503,'text/plain','Add TIKTOK_CLIENT_KEY and TIKTOK_CLIENT_SECRET to the server environment.');const state=crypto.randomBytes(24).toString('hex');states.set(state,Date.now()+600000);const q=new URLSearchParams({client_key:KEY,response_type:'code',scope:'user.info.basic',redirect_uri:REDIRECT,state});res.writeHead(302,{Location:'https://www.tiktok.com/v2/auth/authorize/?'+q});return res.end()}
if(u.pathname==='/auth/tiktok/callback'){const state=u.searchParams.get('state'),code=u.searchParams.get('code');if(!state||states.get(state)<Date.now()||!code)return send(res,400,'text/plain','TikTok authorization was not completed.');states.delete(state);try{const form=new URLSearchParams({client_key:KEY,client_secret:SECRET,code,grant_type:'authorization_code',redirect_uri:REDIRECT});const rr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form}),d=await rr.json();if(!rr.ok||d.error)throw Error(d.error_description||d.error||'Token exchange failed');const id=crypto.randomBytes(32).toString('hex');sessions.set(id,{tiktok:d,created:Date.now()});res.setHeader('Set-Cookie',`sid=${id}; HttpOnly; SameSite=Lax; Secure; Path=/; Max-Age=604800`);res.writeHead(302,{Location:'/?connected=1'});return res.end()}catch(e){return send(res,502,'text/plain','TikTok connection failed: '+e.message)}}
if(req.method==='POST'&&u.pathname==='/api/ai/reply'){let b='';for await(const c of req)b+=c;let x={};try{x=JSON.parse(b)}catch{}const text=String(x.text||'').trim().slice(0,1200);if(!text)return json(res,400,{error:'text required'});const language=['ur','pa','en'].includes(x.language)?x.language:'ur';if(!AI_CONFIGURED){const r={ur:'جی بالکل! میں سارا ہوں، آپ کی بات سن رہی ہوں۔ 💜',pa:'ہاں جی بالکل! میں سارا آں، تہاڈی گل سن رہی آں۔ 💜',en:'Absolutely! I am SARA, your AI virtual host. 💜'};return json(res,200,{reply:r[language],aiConfigured:false})}try{const id=aisid(req,res),h=aiSessions.get(id)||[];h.push({role:'user',content:text});const reply=await askAI(h.slice(-10),language);h.push({role:'assistant',content:reply});aiSessions.set(id,h.slice(-10));return json(res,200,{reply,aiConfigured:true,model:OPENAI_MODEL})}catch(e){return json(res,502,{error:'AI generation failed',detail:e.message})}}
if(req.method==='POST'&&u.pathname==='/api/voice'){if(!VOICE_CONFIGURED)return json(res,503,{error:'Voice is not configured. Add VOICE_PROVIDER, VOICE_API_KEY and VOICE_ID.'});let b='';for await(const c of req)b+=c;let x={};try{x=JSON.parse(b)}catch{}const text=String(x.text||'').trim();if(!text)return json(res,400,{error:'text required'});if(VOICE_PROVIDER!=='elevenlabs')return json(res,501,{error:'Only ElevenLabs is wired in this version.'});try{const lang={ur:'urd',pa:'pan',en:'eng'}[String(x.language||'ur')]||'urd';const rr=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(process.env.VOICE_ID)}`,{method:'POST',headers:{'xi-api-key':process.env.VOICE_API_KEY,'Content-Type':'application/json','Accept':'audio/mpeg'},body:JSON.stringify({text,model_id:'eleven_v3',language_code:lang,voice_settings:{stability:.48,similarity_boost:.8,speed:.98}})}),audio=Buffer.from(await rr.arrayBuffer());if(!rr.ok)return send(res,502,'application/json',audio.toString());res.writeHead(200,{'Content-Type':'audio/mpeg','Cache-Control':'no-store'});return res.end(audio)}catch(e){return json(res,502,{error:'Voice generation failed',detail:e.message})}}
if(u.pathname==='/'||u.pathname==='/index.html')return send(res,200,'text/html; charset=utf-8',fs.readFileSync(path.join(__dirname,'public','index.html')));send(res,404,'text/plain','Not found')});if(require.main===module)server.listen(PORT,()=>console.log('SARA AI LIVE on port '+PORT));module.exports=server;
