const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');
const PORT=Number(process.env.PORT||3000);const KEY=process.env.TIKTOK_CLIENT_KEY||'';const SECRET=process.env.TIKTOK_CLIENT_SECRET||'';const REDIRECT=process.env.TIKTOK_REDIRECT_URI||`http://localhost:${PORT}/auth/tiktok/callback`;const VOICE_PROVIDER=process.env.VOICE_PROVIDER||'';const VOICE_CONFIGURED=!!(VOICE_PROVIDER&&process.env.VOICE_API_KEY&&process.env.VOICE_ID);const sessions=new Map();const states=new Map();
const send=(r,s,t,b)=>{r.writeHead(s,{'Content-Type':t});r.end(b)};const json=(r,s,b)=>send(r,s,'application/json',JSON.stringify(b));
function sid(r){const c=r.headers.cookie||'';const m=c.match(/(?:^|; )sid=([^;]+)/);return m&&m[1]}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);
if(u.pathname==='/api/health')return json(res,200,{ok:true,service:'sara-ai-tiktok-live',tiktokOAuthConfigured:!!(KEY&&SECRET),voiceConfigured:VOICE_CONFIGURED,voiceProvider:VOICE_PROVIDER||null});
if(u.pathname==='/api/me')return json(res,200,{authenticated:!!(sid(req)&&sessions.has(sid(req)))});
if(u.pathname==='/auth/tiktok'){if(!KEY||!SECRET)return send(res,503,'text/plain','Add TIKTOK_CLIENT_KEY and TIKTOK_CLIENT_SECRET to the server environment.');const state=crypto.randomBytes(24).toString('hex');states.set(state,Date.now()+600000);const q=new URLSearchParams({client_key:KEY,response_type:'code',scope:'user.info.basic',redirect_uri:REDIRECT,state});res.writeHead(302,{Location:'https://www.tiktok.com/v2/auth/authorize/?'+q});return res.end()}
if(u.pathname==='/auth/tiktok/callback'){const state=u.searchParams.get('state');const code=u.searchParams.get('code');if(!state||states.get(state)<Date.now()||!code)return send(res,400,'text/plain','TikTok authorization was not completed.');states.delete(state);try{const form=new URLSearchParams({client_key:KEY,client_secret:SECRET,code,grant_type:'authorization_code',redirect_uri:REDIRECT});const rr=await fetch('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:form});const data=await rr.json();if(!rr.ok||data.error)throw Error(data.error_description||data.error||'Token exchange failed');const id=crypto.randomBytes(32).toString('hex');sessions.set(id,{tiktok:data,created:Date.now()});res.setHeader('Set-Cookie',`sid=${id}; HttpOnly; SameSite=Lax; Secure; Path=/; Max-Age=604800`);res.writeHead(302,{Location:'/?connected=1'});return res.end()}catch(e){return send(res,502,'text/plain','TikTok connection failed: '+e.message)}}
if(req.method==='POST'&&u.pathname==='/api/ai/reply'){let b='';for await(const c of req)b+=c;let x={};try{x=JSON.parse(b)}catch{}const text=String(x.text||'').trim();if(!text)return json(res,400,{error:'text required'});const replies={ur:'جی بالکل! میں سارا ہوں، آپ کی بات سن رہی ہوں۔ 💜',pa:'ہاں جی بالکل! میں سارا آں، تہاڈی گل سن رہی آں۔ 💜',en:'Absolutely! I am SARA, your AI virtual host. 💜'};return json(res,200,{reply:replies[x.language]||replies.ur})}
if(u.pathname==='/'||u.pathname==='/index.html'){return send(res,200,'text/html; charset=utf-8',fs.readFileSync(path.join(__dirname,'public','index.html')))}send(res,404,'text/plain','Not found')});
if(require.main===module)server.listen(PORT,()=>console.log('SARA AI LIVE on port '+PORT));module.exports=server;
