const C=(e,x={})=>({"Access-Control-Allow-Origin":e.FRONTEND_ORIGIN||"*","Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"GET,POST,OPTIONS",...x});
const J=(e,d,s=200,x={})=>new Response(JSON.stringify(d),{status:s,headers:C(e,{"Content-Type":"application/json",...x})});
const T=(e,d,s=200)=>new Response(d,{status:s,headers:C(e,{"Content-Type":"text/plain"})});
const ck=(r,n)=>{for(const p of(r.headers.get("Cookie")||"").split(";")){const a=p.trim().split("=");if(a[0]===n)return decodeURIComponent(a.slice(1).join("="))}return""};
const sc=(n,v,a)=>n+"="+encodeURIComponent(v)+"; HttpOnly; Secure; SameSite=None; Path=/; Max-Age="+a;
const b64=a=>{let s="",u=new Uint8Array(a);for(let i=0;i<u.length;i+=32768)s+=String.fromCharCode(...u.subarray(i,i+32768));return btoa(s)};
const get=async(e,k)=>{let v=await e.SARA_KV.get(k);return v?JSON.parse(v):null};
const put=async(e,k,v,t=86400)=>e.SARA_KV.put(k,JSON.stringify(v),{expirationTtl:t});
async function mac(s,v){let k=await crypto.subtle.importKey("raw",new TextEncoder().encode(s),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(v))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function ai(e,h){let r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:"Bearer "+e.OPENAI_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({model:e.OPENAI_MODEL||"gpt-5.6",instructions:"You are SARA, a Pakistani female AI virtual host. You are AI, never claim human. Reply ONLY in Urdu. Understand Roman Urdu, Urdu, Punjabi and Pakistani English. Keep replies 1-3 friendly sentences. Never pressure gifts or spending. Never invent live data.",input:h.slice(-10),max_output_tokens:180})});let d=await r.json();if(!r.ok)throw Error(d.error?.message||"OpenAI failed");return String(d.output_text||"").trim()}
async function voice(e,t){if(!e.VOICE_API_KEY||!e.VOICE_ID)return null;let r=await fetch("https://api.elevenlabs.io/v1/text-to-speech/"+encodeURIComponent(e.VOICE_ID)+"?output_format=pcm_24000",{method:"POST",headers:{"xi-api-key":e.VOICE_API_KEY,"Content-Type":"application/json","Accept":"audio/pcm"},body:JSON.stringify({text:t,model_id:"eleven_v3",language_code:"ur"})});let a=await r.arrayBuffer();if(!r.ok)throw Error("ElevenLabs failed");return{audioBase64:b64(a),format:"pcm_24000"}}
export default{async fetch(r,e){
if(r.method==="OPTIONS")return new Response(null,{status:204,headers:C(e)});
let u=new URL(r.url);
if(u.pathname==="/api/health")return J(e,{ok:true,service:"sara-live-cloudflare",aiConfigured:!!e.OPENAI_API_KEY,voiceConfigured:!!(e.VOICE_API_KEY&&e.VOICE_ID),liveAvatarConfigured:!!(e.LIVEAVATAR_API_KEY&&e.LIVEAVATAR_AVATAR_ID),tiktokOAuthConfigured:!!(e.TIKTOK_CLIENT_KEY&&e.TIKTOK_CLIENT_SECRET),tiktokRedirectUri:e.TIKTOK_REDIRECT_URI||new URL("/auth/tiktok/callback",r.url).toString(),liveInteractionApi:false});
if(u.pathname==="/api/me"){let id=ck(r,"sara_sid"),s=id?await get(e,"session:"+id):null;return J(e,{authenticated:!!s,openId:s?.tiktok?.open_id||null,scope:s?.tiktok?.scope||null})}
if(u.pathname==="/api/sara/message"&&r.method==="POST"){if(!e.OPENAI_API_KEY)return J(e,{error:"AI is not configured"},503);let id=ck(r,"ai_sid")||b64(crypto.getRandomValues(new Uint8Array(16))),s=await get(e,"ai:"+id)||{history:[]},q=await r.json().catch(()=>({}));if(!String(q.text||"").trim())return J(e,{error:"text required"},400);let h=[...(s.history||[]),{role:"user",content:String(q.text).trim().slice(0,1200)}],reply=await ai(e,h);s.history=[...h,{role:"assistant",content:reply}].slice(-10);await put(e,"ai:"+id,s);let v=null;try{v=await voice(e,reply)}catch{}return J(e,{ok:true,reply,...(v||{})},200,{"Set-Cookie":sc("ai_sid",id,86400)})}
if(u.pathname==="/api/liveavatar/token"&&r.method==="POST"){if(!e.LIVEAVATAR_API_KEY||!e.LIVEAVATAR_AVATAR_ID)return J(e,{error:"LiveAvatar is not configured"},503);let r2=await fetch("https://api.liveavatar.com/v1/sessions/token",{method:"POST",headers:{"X-API-KEY":e.LIVEAVATAR_API_KEY,"Content-Type":"application/json"},body:JSON.stringify({mode:"LITE",avatar_id:e.LIVEAVATAR_AVATAR_ID,is_sandbox:String(e.LIVEAVATAR_IS_SANDBOX||"false")==="true"})}),d=await r2.json();if(!r2.ok)return J(e,{error:d?.data?.message||"LiveAvatar failed"},502);return J(e,{ok:true,session_token:d?.data?.session_token,session_id:d?.data?.session_id||null,avatar_id:e.LIVEAVATAR_AVATAR_ID})}
if(u.pathname==="/auth/tiktok"){if(!e.TIKTOK_CLIENT_KEY||!e.TIKTOK_CLIENT_SECRET)return T(e,"TikTok credentials are not configured",503);let n=b64(crypto.getRandomValues(new Uint8Array(32))),st=n+"."+await mac(e.TIKTOK_CLIENT_SECRET,n),q=new URLSearchParams({client_key:e.TIKTOK_CLIENT_KEY,response_type:"code",scope:e.TIKTOK_SCOPES||"user.info.basic",redirect_uri:e.TIKTOK_REDIRECT_URI||new URL("/auth/tiktok/callback",r.url).toString(),state:st});return new Response(null,{status:302,headers:{Location:"https://www.tiktok.com/v2/auth/authorize/?"+q.toString(),"Set-Cookie":sc("tt_oauth_state",n,600)}})}
if(u.pathname==="/auth/tiktok/callback"){let st=u.searchParams.get("state"),code=u.searchParams.get("code"),cookie=ck(r,"tt_oauth_state");if(!st||!code||st.split(".")[0]!==cookie||st.split(".")[1]!==await mac(e.TIKTOK_CLIENT_SECRET,cookie))return T(e,"TikTok authorization state is invalid or expired",400);let f=new URLSearchParams({client_key:e.TIKTOK_CLIENT_KEY,client_secret:e.TIKTOK_CLIENT_SECRET,code,grant_type:"authorization_code",redirect_uri:e.TIKTOK_REDIRECT_URI||new URL("/auth/tiktok/callback",r.url).toString()}),rr=await fetch("https://open.tiktokapis.com/v2/oauth/token/",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:f}),d=await rr.json();if(!rr.ok||d.error)return T(e,"TikTok connection failed: "+(d.error_description||d.error||"token error"),502);let id=b64(crypto.getRandomValues(new Uint8Array(32))),s={id,tiktok:{...d,access_token_expires_at:Date.now()+Number(d.expires_in||86400)*1000}};await put(e,"session:"+id,s,604800);let front=(e.FRONTEND_ORIGIN||new URL("/",r.url).origin).replace(/\/$/,"");return new Response(null,{status:302,headers:{Location:front+"/?connected=1&backend="+encodeURIComponent(new URL(r.url).origin),"Set-Cookie":sc("sara_sid",id,604800)}})}
return T(e,"Not found",404)
}};